config/routes.rb
Rails.application.routes.draw do
  get 'welecome/index'

  resources :articles
  root 'welecome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect
    # @article = Article.new(params[:article])
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end

  end

  private
    def article_params
      params.require(:article).permit(:title,:text)
    end
end

app/controllers/welecome_controller.rb
class WelecomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welecome_helper.rb
module WelecomeHelper
end

app/views/articles/index.html.erb
<h1>List Articles</h1>

<%= link_to 'New article', new_article_path %>

<br><br>

<table>
  <tr>
    <th>title</th>
    <th>text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>

</table>

app/views/articles/new.html.erb
<h1>Add Article</h1>

<%= link_to 'Back', articles_path %>

<br>
<%= form_for :article,url: articles_path do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h3>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit%>
    </p>
<% end %>

app/views/articles/show.html.erb
<h1>Show Article</h1>
<%= link_to 'Back', articles_path %>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welecome/index.html.erb
<h1>Welecome to you</h1>

<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>